### ISSUE TITLE
filter config error

### ISSUE THREAD

**Issue by jxxbd91** [owlsdepartment/vite-plugin-babel#1]
vite got error `Error: [babel] "onLoad" filter is not a valid Go regular expression: "^((?!(\\.vue|vue\\-demi|\\.md)).)*\\.(js|ts|jsx|tsx)$"` when i passed `filter` config as `/^((?!(\.vue|vue\-demi|\.md)).)*\.(js|ts|jsx|tsx)$/`
the whole config is like:
```javascript
babel({
      babelConfig: {
        plugins: [
          '@babel/plugin-transform-runtime',
          ['@babel/plugin-transform-typescript', { isTSX: true, allowExtensions: true }],
        ],
        presets: ['vca-jsx', '@vue/babel-preset-jsx'],
      },
      filter: /^((?!(\.vue|vue\-demi|\.md)).)*\.(js|ts|jsx|tsx)$/,
})
```

the error msg is:

```
Debugger attached.
error when starting dev server:
Error: [babel] "onLoad" filter is not a valid Go regular expression: "^((?!(\\.vue|vue\\-demi|\\.md)).)*\\.(js|ts|jsx|tsx)$"
    at /Users/jin.shenmin/pro/lego/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1237:25
    at /Users/jin.shenmin/pro/lego/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/jin.shenmin/pro/lego/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:724:9)
    at Socket.readFromStdout (/Users/jin.shenmin/pro/lego/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

i supposed golang not support the regular expression like `((?!(\.vue|vue\-demi|\.md)).)` which can worked fine in javascript

**Comment by F0rsaken** [comment]
You can also test your RegEx on https://regex101.com/ , but remember to choose language `Go` in left sidebar

**Comment by F0rsaken** [comment]
Closing it as no new infos are coming
