### ISSUE TITLE
Error during build - babel is not a function

### ISSUE THREAD

**Issue by DylanMashini** [owlsdepartment/vite-plugin-babel#5]
Getting this error on build:
```failed to load config from /home/projects/vitejs-vite-amhmw2/vite.config.js
error during build:
Error: _vite_plugin_babel.default is not a function
    at async doBuild (file:///home/projects/vitejs-vite-amhmw2/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:43462:20)
    at async build (file:///home/projects/vitejs-vite-amhmw2/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:43451:16)
    at async CAC.eval (file:///home/projects/vitejs-vite-amhmw2/node_modules/vite/dist/node/cli.js:758:9)
```

Vite Version: 2
Node Version: 16.4.2
@babel/core version: ^7.18.10

Here's a minimum reproduceable example: https://stackblitz.com/edit/vitejs-vite-amhmw2?file=vite.config.js

**Comment by F0rsaken** [comment]
Thanks for reproduction! If you remove `"type": "module"` from `package.json` it will work for now, but I will make a release of this package that will support it

**Comment by F0rsaken** [comment]
@DylanMashini new version `1.1.1` was published and should now fix your problem and support `"type": "module"`
